export const formFieldHeadings = {
  FullStack: {
    GIT: [
      "creating a repo",
      "git flow",
      "feature branches",
      "pull merge add commit push repeat",
      "additional git commands and scenarios",
    ],
    HTML: ["tags, elements, attributes", "wireframes", "semantic html and mdn"],
    CSS: [
      "linking and import",
      "selectors (id, classes/attributes, tag) ",
      "specificity",
      "how to style with box model",
      "colors, borders, shadows",
      "positioning",
      "flex and grid",
    ],
    JS: [
      "linking js files",
      "es6 imports",
      "DOM and BOM",
      "nodes vs html collection",
      "selectors ",
      "events ",
      "asynchronicity and promises",
      "request response cycle,",
    ],
    BACKEND: ["database schema"],
    SQL: ["PSQL and postgres"],
    FLASK: [
      "creating a server and app.py",
      "application structure",
      "routing and restful endpoints",
      "blueprints",
    ],
    FLASKSQLALCHEMY: ["models, migrations, seeders", "env and flaskenv files"],
    AUTH: ["cors and forms", "hashed passwords and validations"],
    IoTs: ["AWS, RaspberryPi, etc"],
    FRAMEWORKS: ["basic fullstack structure"],
    REACT: [
      "create react app",
      "state",
      "component structure",
      "file structure",
      "hooks",
      "context global state",
      "redux",
      "actions, action creators, thunks",
      "redux vs context",
    ],
  },
  Python: {
    GIT: [
      "creating a repo",
      "git flow",
      "feature branches",
      "pull merge add commit push repeat",
      "additional git commands and scenarios",
    ],
    BASICS: [
      "variables",
      "data types",
      "functions",
      "data structures",
      "classes",
    ],
    ADVANCED: ["comprehensions", "data structures and algorithms"],
    Pi: ["Intro to Pi", "RaspberryPi Project"],
  },
};
